### PR TITLE
Fix errors by commenting out bridge & fix beautiful soup

### PR DESCRIPTION
**Pull request by Clete2**
It looks like you meant to add functionality to customize the bridge, but I was getting errors when trying to login.

Additionally, you switched to `bs4` elsewhere but forgot to switch to `bs4` in `backend_config.py`.

### CODE REVIEW

**Comment by lakewik** [comment]
@Clete2 What errors are you getting when trying to login?

**Comment by Clete2** [comment]
`storj_bridge` on `storj.Client` is undefined and `bridge_api_url` on `login` is undefined.

If you need more details, let me know and I can run again.

And the last file I changed really was supposed to go into my other pull request. I changed to `bs4` because you had moved to `bs4` from `beautifulsoup` and had forgotten to change that file.

**Comment by marcorosa** [comment]
`storj_bridge` on `storj.Client` [is defined](https://github.com/Storj/storj-python-sdk/blob/cd2b5fa1a906e8cf8b49333e1b415893caa444a9/storj/http.py#L65)

**Comment by marcorosa** [comment]
We just had to update `requirements.txt` file in order to use storj version 0.3.14 instead of 0.3.12
Commit [a7e0dcf](https://github.com/lakewik/storj_gui_client/commit/a7e0dcf6005a29f78eab08343ba4305b9a7faf3d) fixes this

**Pull request closed without merging**
